### ISSUE TITLE
Export event tester + export "ignore all listeners" helper

### ISSUE THREAD

**Issue by broofa** [fregante/filter-altered-clicks#1]
Nice lib!  A few first impressions ...

Since these are normally called  ["modifier" keys](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#modifier_keys), my brain really wants the name to be filter-_modified_-clicks. 

The real "meat" of this module is the "is this event modified?" logic, [here](https://github.com/fregante/filter-altered-clicks/blob/master/index.js#L5-L9).  I'm pretty sure there's a need for this beyond filtering link clicks.  Thus, it might be worth exposing an `isModifiedEvent(e)` method.

Having to add the filterAlteredClicks method to every link event handler feels a bit kludgy.   What about something like the following as a generalized, deal-with-all-modified link clicks handler?  (Note:  I'm generally skeptical of kludgy JS code like this that tries to simulate native browser behavior.  It almost always misses some important nuance that ends up being problematic. But... maybe this will do the trick?)

```javascript
function enableModifiedLinkClicks() {
  document.addEventListener('click', e => {
    // Ignore any events that aren't modified link clicks
    if (e.target.nodeName != 'A' || !isModifiedEvent(e)) return;

    // Stop processing this event
    e.preventDefault();
    e.stopPropagation();

    // Perform the click on a new link (sans-event handlers)
    const el = document.createElement('a');
    el.href = e.target.href;
    el.dispatchEvent(new MouseEvent("click", e));
  }, true);
}
```

**Comment by fregante** [comment]
This module is uses `altered` because it doesn't just look at modifiers, but can also exclude already-handled events via `isDefaultPrevented`

> a generalized, deal-with-all-modified link clicks handler

Yeah that sounds like an interesting solution to disable _all_ listeners. As mentioned however an inlined `filterAlteredClicks(handler)` can also be used the opposite way: ignore any events that have already been handled/altered, either by another event listener that called `preventDefault()` or by the user by middle-clicking for example (which isn't strictly _modified_ either)

**Comment by broofa** [comment]
[Closing out issues I've authored that appear to be stagnant.]
